import '../public/globals.sass'

import { Inter } from 'next/font/google'

import Header from '@/components/Header/Header'
import Footer from '@/components/Footer/Footer'


const inter = Inter( { subsets: [ 'latin' ] } )


export const metadata = {

    title       : 'Admin - Santral Kumpanya',
    description : 'Generated by create next app',
}


export default function RootLayout( { children } )
{
    return (

        <html lang="en">
            <body className={ inter.className }>
                <Header />

                <main>
                    { children }

                    <Footer />
                </main>
            </body>
        </html>

    )
}